FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && \
    apt-get install -y git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY ./app/requirements ./requirements

RUN pip install --no-cache-dir -r requirements/dev.txt

COPY ./app .

CMD ["sh", "-c", "celery -A config.celery.celery_app worker --loglevel=info --queues=boiler_plate_queue"]