"""created usermodel

Revision ID: 47baa88917bd
Revises: 49fc9138e137
Create Date: 2025-10-11 12:05:10.669699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47baa88917bd'
down_revision: Union[str, None] = '49fc9138e137'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_password_changed_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'password',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('users', 'last_password_changed_at')
    # ### end Alembic commands ###
