"""created user invitationmodel

Revision ID: 51b5461cb727
Revises: 587649837fb4
Create Date: 2025-12-20 15:14:02.939252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51b5461cb727'
down_revision: Union[str, None] = '587649837fb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_invitations',
    sa.Column('user_invitation_id', sa.UUID(), nullable=False),
    sa.Column('user_invitation_email', sa.String(length=200), nullable=False),
    sa.Column('user_invitation_first_name', sa.String(length=100), nullable=False),
    sa.Column('user_invitation_last_name', sa.String(length=100), nullable=True),
    sa.Column('user_invitation_role', sa.UUID(), nullable=False),
    sa.Column('user_invitation_tenant_id', sa.UUID(), nullable=False),
    sa.Column('is_user_invitation_accepted', sa.Boolean(), nullable=True),
    sa.Column('user_invitation_designation', sa.String(length=50), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_invitation_role'], ['roles.role_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_invitation_tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_invitation_id')
    )
    op.create_index(op.f('ix_user_invitations_user_invitation_email'), 'user_invitations', ['user_invitation_email'], unique=True)
    op.create_index(op.f('ix_user_invitations_user_invitation_id'), 'user_invitations', ['user_invitation_id'], unique=True)
    op.create_index(op.f('ix_user_invitations_user_invitation_tenant_id'), 'user_invitations', ['user_invitation_tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_invitations_user_invitation_tenant_id'), table_name='user_invitations')
    op.drop_index(op.f('ix_user_invitations_user_invitation_id'), table_name='user_invitations')
    op.drop_index(op.f('ix_user_invitations_user_invitation_email'), table_name='user_invitations')
    op.drop_table('user_invitations')
    # ### end Alembic commands ###
