"""updated user model

Revision ID: 587649837fb4
Revises: 47baa88917bd
Create Date: 2025-12-18 14:04:01.000465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '587649837fb4'
down_revision: Union[str, None] = '47baa88917bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('soft_deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('users', 'soft_teleted_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('soft_teleted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('users', 'soft_deleted_at')
    # ### end Alembic commands ###
