"""created tenant model

Revision ID: a7adc2100aa7
Revises: 
Create Date: 2025-10-05 11:40:50.266924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7adc2100aa7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('tenant_name', sa.String(length=100), nullable=False),
    sa.Column('tenant_code', sa.String(length=15), nullable=False),
    sa.Column('tenant_email', sa.String(length=200), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('tenant_logo', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('soft_teleted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('tenant_id'),
    sa.UniqueConstraint('tenant_code')
    )
    op.create_index(op.f('ix_tenants_tenant_id'), 'tenants', ['tenant_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_tenant_id'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
